### ISSUE TITLE
Remove withdraw_bitcoins() from documentation and tests

### ISSUE THREAD

**Issue by mutant-industries** [rrguardo/coinmate.io-api#1]
You don't put things like `cm_api.withdraw_bitcoins(2,'1HB1by2ZkbFAwEAqC5zwoHcU1DroBysrPG')` to random five places in documentation and tests.

**Comment by rrguardo** [comment]
Thanks for the recommendations, 
for now we decrease the withdrawal amount used at samples and use a more know public BTC address.

Anyway the withdraw samples and tests will continue yet there, because are an important part of documentation and test.
  
Note that tests run in mock servers without real danger by default and documentation should contain withdraw examples. (My main usage of this client is for automatic withdraws)
